import type { StylesheetJson } from 'cytoscape'

export const GRAPH_STYLES: StylesheetJson = [
  {
    selector: 'node',
    style: {
      'background-color': '#718096',
      'border-color': '#ffffff',
      'border-width': 2,
      'color': '#2d3748',
      'font-family': 'Inter, ui-sans-serif, system-ui, sans-serif',
      'font-size': 9,
      'label': 'data(label)',
      'text-background-color': '#ffffff',
      'text-background-opacity': 0,
      'text-background-padding': '4px',
      'text-max-width': '180px',
      'text-opacity': 0,
      'text-overflow-wrap': 'anywhere',
      'text-wrap': 'wrap',
      'text-valign': 'bottom',
      'text-margin-y': 7,
      'width': 25,
      'height': 25,
    },
  },
  { selector: 'node.project', style: { 'background-color': '#9b6a2b', 'shape': 'diamond', 'width': 36, 'height': 36 } },
  { selector: 'node.hovered, node:selected', style: { 'text-background-opacity': 0.96, 'text-opacity': 1, 'z-index': 20 } },
  { selector: 'node.objective, node.requirement, node.task', style: { 'background-color': '#6877a6' } },
  { selector: 'node.source, node.evidence', style: { 'background-color': '#3d8b73' } },
  { selector: 'node.claim', style: { 'background-color': '#8b5f9c' } },
  { selector: 'node.artifact, node.review, node.decision', style: { 'background-color': '#c88428' } },
  { selector: 'node.event, node.note', style: { 'background-color': '#87909d', 'width': 18, 'height': 18 } },
  { selector: 'node.status-blocked, node.status-contested, node.status-unverified, node.status-open', style: { 'border-color': '#d45d4c', 'border-width': 4 } },
  { selector: 'node:selected', style: { 'border-color': '#1f2937', 'border-width': 4, 'overlay-color': '#c88428', 'overlay-opacity': 0.12 } },
  {
    selector: 'edge',
    style: {
      'arrow-scale': 0.7,
      'curve-style': 'bezier',
      'line-color': '#a8b0bb',
      'opacity': 0.42,
      'target-arrow-color': '#a8b0bb',
      'target-arrow-shape': 'triangle',
      'width': 1,
    },
  },
  { selector: 'edge:selected', style: { 'line-color': '#c88428', 'target-arrow-color': '#c88428', 'opacity': 1, 'width': 2.4 } },
]
