import type { StylesheetJson } from 'cytoscape'

export const GRAPH_STYLES: StylesheetJson = [
  {
    selector: 'node',
    style: {
      'background-color': '#718096',
      'border-color': '#ffffff',
      'border-width': 2,
      'color': '#2d3748',
      'font-family': 'Inter, ui-sans-serif, system-ui, sans-serif',
      'font-size': 9,
      'label': 'data(label)',
      'text-background-color': '#ffffff',
      'text-background-opacity': 0,
      'text-background-padding': '4px',
      'text-max-width': '180px',
      'text-opacity': 0,
      'text-overflow-wrap': 'anywhere',
      'text-wrap': 'wrap',
      'text-valign': 'bottom',
      'text-margin-y': 7,
      'width': 25,
      'height': 25,
    },
  },
  { selector: 'node.project', style: { 'background-color': '#9b6a2b', 'shape': 'diamond', 'width': 36, 'height': 36 } },
  { selector: 'node.objective', style: { 'background-color': '#6877a6', 'shape': 'hexagon' } },
  { selector: 'node.requirement', style: { 'background-color': '#6877a6', 'shape': 'round-rectangle' } },
  { selector: 'node.task', style: { 'background-color': '#6877a6', 'shape': 'rectangle' } },
  { selector: 'node.source', style: { 'background-color': '#3d8b73', 'shape': 'ellipse' } },
  { selector: 'node.evidence', style: { 'background-color': '#3d8b73', 'shape': 'triangle' } },
  { selector: 'node.claim', style: { 'background-color': '#8b5f9c', 'shape': 'octagon' } },
  { selector: 'node.artifact', style: { 'background-color': '#c88428', 'shape': 'rhomboid' } },
  { selector: 'node.review', style: { 'background-color': '#c88428', 'shape': 'vee' } },
  { selector: 'node.decision', style: { 'background-color': '#c88428', 'shape': 'star' } },
  { selector: 'node.event, node.note', style: { 'background-color': '#87909d', 'shape': 'tag', 'width': 18, 'height': 18 } },
  { selector: 'node.note', style: { 'shape': 'barrel' } },
  { selector: 'node.hovered, node:selected, node.focused', style: { 'text-background-opacity': 0.96, 'text-opacity': 1, 'z-index': 20 } },
  { selector: 'node.search-match', style: { 'border-color': '#c88428', 'border-width': 3, 'text-background-opacity': 0.96, 'text-opacity': 1, 'z-index': 19 } },
  { selector: 'node.related', style: { 'text-background-opacity': 0.86, 'text-opacity': 0.82, 'z-index': 10 } },
  { selector: 'node.dimmed', style: { 'opacity': 0.16, 'text-opacity': 0 } },
  { selector: 'edge.dimmed', style: { 'opacity': 0.06 } },
  { selector: 'node.focused', style: { 'border-color': '#1f2937', 'border-width': 4, 'overlay-color': '#c88428', 'overlay-opacity': 0.12 } },
  { selector: 'node.status-blocked, node.status-contested, node.status-unverified, node.status-open', style: { 'border-color': '#d45d4c', 'border-width': 4 } },
  { selector: 'node:selected', style: { 'border-color': '#1f2937', 'border-width': 4, 'overlay-color': '#c88428', 'overlay-opacity': 0.12 } },
  {
    selector: 'edge',
    style: {
      'arrow-scale': 0.7,
      'curve-style': 'bezier',
      'line-color': '#a8b0bb',
      'opacity': 0.42,
      'target-arrow-color': '#a8b0bb',
      'target-arrow-shape': 'triangle',
      'width': 1,
      'text-opacity': 0,
    },
  },
  { selector: 'edge.edge-kind-contains', style: { 'line-style': 'solid', 'target-arrow-shape': 'triangle' } },
  { selector: 'edge.edge-kind-addresses', style: { 'line-style': 'dashed', 'target-arrow-shape': 'vee' } },
  { selector: 'edge.edge-kind-depends_on', style: { 'line-style': 'dotted', 'target-arrow-shape': 'triangle' } },
  { selector: 'edge.edge-kind-produces', style: { 'line-style': 'solid', 'target-arrow-shape': 'diamond' } },
  { selector: 'edge.edge-kind-derived_from', style: { 'line-style': 'dashed', 'target-arrow-shape': 'triangle' } },
  { selector: 'edge.edge-kind-supports', style: { 'line-style': 'solid', 'target-arrow-shape': 'vee' } },
  { selector: 'edge.edge-kind-contradicts', style: { 'line-style': 'dashed', 'target-arrow-shape': 'tee' } },
  { selector: 'edge.edge-kind-cites', style: { 'line-style': 'dotted', 'target-arrow-shape': 'triangle' } },
  { selector: 'edge.edge-kind-reviews', style: { 'line-style': 'dashed', 'target-arrow-shape': 'diamond' } },
  { selector: 'edge.edge-kind-resolves', style: { 'line-style': 'solid', 'target-arrow-shape': 'tee' } },
  { selector: 'edge.edge-kind-supersedes', style: { 'line-style': 'solid', 'target-arrow-shape': 'vee' } },
  { selector: 'edge.edge-kind-affects', style: { 'line-style': 'dotted', 'target-arrow-shape': 'circle' } },
  { selector: 'edge.related', style: { 'line-color': '#c88428', 'target-arrow-color': '#c88428', 'opacity': 0.95, 'width': 2.4, 'label': 'data(label)', 'color': '#8b5f1d', 'font-size': 8, 'text-background-color': '#ffffff', 'text-background-opacity': 0.9, 'text-background-padding': '3px', 'text-rotation': 'autorotate' } },
  { selector: 'edge:selected', style: { 'line-color': '#c88428', 'target-arrow-color': '#c88428', 'opacity': 1, 'width': 2.4 } },
]
